[2024-11-23T18:20:23.356+0200] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-23T18:20:23.369+0200] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_time_patient_data_update.fetch_all_patient_data scheduled__2024-11-23T16:15:00+00:00 [queued]>
[2024-11-23T18:20:23.397+0200] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_time_patient_data_update.fetch_all_patient_data scheduled__2024-11-23T16:15:00+00:00 [queued]>
[2024-11-23T18:20:23.398+0200] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-23T18:20:23.416+0200] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_all_patient_data> on 2024-11-23 16:15:00+00:00
[2024-11-23T18:20:23.422+0200] {standard_task_runner.py:72} INFO - Started process 394277 to run task
[2024-11-23T18:20:23.428+0200] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'real_time_patient_data_update', 'fetch_all_patient_data', 'scheduled__2024-11-23T16:15:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/real_time_patient_data_update.py', '--cfg-path', '/tmp/tmpv3lh2kcp']
[2024-11-23T18:20:23.430+0200] {standard_task_runner.py:105} INFO - Job 2: Subtask fetch_all_patient_data
[2024-11-23T18:20:23.487+0200] {task_command.py:467} INFO - Running <TaskInstance: real_time_patient_data_update.fetch_all_patient_data scheduled__2024-11-23T16:15:00+00:00 [running]> on host munyah-ThinkPad-X1-Yoga-1st
[2024-11-23T18:20:23.606+0200] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='real_time_patient_data_update' AIRFLOW_CTX_TASK_ID='fetch_all_patient_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T16:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-23T16:15:00+00:00'
[2024-11-23T18:20:23.608+0200] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-23T18:20:23.608+0200] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-23T18:20:23.608+0200] {logging_mixin.py:190} INFO - Current task name:fetch_all_patient_data state:running start_date:2024-11-23 16:20:23.369476+00:00
[2024-11-23T18:20:23.609+0200] {logging_mixin.py:190} INFO - Dag name:real_time_patient_data_update and current dag run status:running
[2024-11-23T18:20:23.609+0200] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-23T18:20:23.621+0200] {base.py:84} INFO - Retrieving connection 'patients_data'
[2024-11-23T18:20:23.642+0200] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/munyah/airflow/dags/real_time_patient_data_update.py", line 20, in fetch_all_patient_data
    df.to_csv(CSV_FILE_PATH, mode='w', header=True, index=False)
  File "/home/munyah/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/munyah/.local/lib/python3.10/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/munyah/.local/lib/python3.10/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/munyah/.local/lib/python3.10/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/home/munyah/.local/lib/python3.10/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/data'
[2024-11-23T18:20:23.658+0200] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-23T18:20:23.659+0200] {logging_mixin.py:190} INFO - Task start:2024-11-23 16:20:23.369476+00:00 end:2024-11-23 16:20:23.658068+00:00 duration:0.288592
[2024-11-23T18:20:23.659+0200] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_all_patient_data> dag:<DAG: real_time_patient_data_update> dagrun:<DagRun real_time_patient_data_update @ 2024-11-23 16:15:00+00:00: scheduled__2024-11-23T16:15:00+00:00, state:running, queued_at: 2024-11-23 16:20:20.251880+00:00. externally triggered: False>
[2024-11-23T18:20:23.659+0200] {logging_mixin.py:190} INFO - Failure caused by Cannot save file into a non-existent directory: '/data'
[2024-11-23T18:20:23.659+0200] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=real_time_patient_data_update, task_id=fetch_all_patient_data, run_id=scheduled__2024-11-23T16:15:00+00:00, execution_date=20241123T161500, start_date=20241123T162023, end_date=20241123T162023
[2024-11-23T18:20:23.678+0200] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-23T18:20:23.679+0200] {standard_task_runner.py:124} ERROR - Failed to execute job 2 for task fetch_all_patient_data (Cannot save file into a non-existent directory: '/data'; 394277)
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/munyah/airflow/dags/real_time_patient_data_update.py", line 20, in fetch_all_patient_data
    df.to_csv(CSV_FILE_PATH, mode='w', header=True, index=False)
  File "/home/munyah/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/munyah/.local/lib/python3.10/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/munyah/.local/lib/python3.10/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/munyah/.local/lib/python3.10/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/home/munyah/.local/lib/python3.10/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/data'
[2024-11-23T18:20:23.724+0200] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-23T18:20:23.754+0200] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-23T18:20:23.755+0200] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-23T18:24:30.004+0200] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-23T18:24:30.016+0200] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_time_patient_data_update.fetch_all_patient_data scheduled__2024-11-23T16:15:00+00:00 [queued]>
[2024-11-23T18:24:30.023+0200] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_time_patient_data_update.fetch_all_patient_data scheduled__2024-11-23T16:15:00+00:00 [queued]>
[2024-11-23T18:24:30.023+0200] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-23T18:24:30.037+0200] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_all_patient_data> on 2024-11-23 16:15:00+00:00
[2024-11-23T18:24:30.044+0200] {standard_task_runner.py:72} INFO - Started process 395016 to run task
[2024-11-23T18:24:30.049+0200] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'real_time_patient_data_update', 'fetch_all_patient_data', 'scheduled__2024-11-23T16:15:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/real_time_patient_data_update.py', '--cfg-path', '/tmp/tmp90oa8ye5']
[2024-11-23T18:24:30.051+0200] {standard_task_runner.py:105} INFO - Job 2: Subtask fetch_all_patient_data
[2024-11-23T18:24:30.089+0200] {task_command.py:467} INFO - Running <TaskInstance: real_time_patient_data_update.fetch_all_patient_data scheduled__2024-11-23T16:15:00+00:00 [running]> on host munyah-ThinkPad-X1-Yoga-1st
[2024-11-23T18:24:30.145+0200] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='real_time_patient_data_update' AIRFLOW_CTX_TASK_ID='fetch_all_patient_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T16:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-23T16:15:00+00:00'
[2024-11-23T18:24:30.147+0200] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-23T18:24:30.147+0200] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-23T18:24:30.147+0200] {logging_mixin.py:190} INFO - Current task name:fetch_all_patient_data state:running start_date:2024-11-23 16:24:30.016348+00:00
[2024-11-23T18:24:30.147+0200] {logging_mixin.py:190} INFO - Dag name:real_time_patient_data_update and current dag run status:running
[2024-11-23T18:24:30.147+0200] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-23T18:24:30.153+0200] {base.py:84} INFO - Retrieving connection 'patients_data'
[2024-11-23T18:24:30.173+0200] {python.py:240} INFO - Done. Returned value was: None
[2024-11-23T18:24:30.181+0200] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-23T18:24:30.181+0200] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=real_time_patient_data_update, task_id=fetch_all_patient_data, run_id=scheduled__2024-11-23T16:15:00+00:00, execution_date=20241123T161500, start_date=20241123T162430, end_date=20241123T162430
[2024-11-23T18:24:30.193+0200] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-23T18:24:30.194+0200] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-23T18:24:30.194+0200] {logging_mixin.py:190} INFO - Dag name:real_time_patient_data_update queued_at:2024-11-23 16:24:27.248708+00:00
[2024-11-23T18:24:30.194+0200] {logging_mixin.py:190} INFO - Task hostname:munyah-ThinkPad-X1-Yoga-1st operator:PythonOperator
[2024-11-23T18:24:30.221+0200] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-23T18:24:30.241+0200] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-23T18:24:30.246+0200] {local_task_job_runner.py:245} INFO - ::endgroup::
