[2024-11-23T19:19:59.094+0200] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-23T19:19:59.106+0200] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_time_patient_data.update_patient_data manual__2024-11-23T17:19:43.702809+00:00 [queued]>
[2024-11-23T19:19:59.114+0200] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_time_patient_data.update_patient_data manual__2024-11-23T17:19:43.702809+00:00 [queued]>
[2024-11-23T19:19:59.115+0200] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-23T19:19:59.129+0200] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): update_patient_data> on 2024-11-23 17:19:43.702809+00:00
[2024-11-23T19:19:59.136+0200] {standard_task_runner.py:72} INFO - Started process 407122 to run task
[2024-11-23T19:19:59.141+0200] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'real_time_patient_data', 'update_patient_data', 'manual__2024-11-23T17:19:43.702809+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/real_time_patient_data_update.py', '--cfg-path', '/tmp/tmpphggv4g_']
[2024-11-23T19:19:59.143+0200] {standard_task_runner.py:105} INFO - Job 5: Subtask update_patient_data
[2024-11-23T19:19:59.182+0200] {task_command.py:467} INFO - Running <TaskInstance: real_time_patient_data.update_patient_data manual__2024-11-23T17:19:43.702809+00:00 [running]> on host munyah-ThinkPad-X1-Yoga-1st
[2024-11-23T19:19:59.251+0200] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='real_time_patient_data' AIRFLOW_CTX_TASK_ID='update_patient_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T17:19:43.702809+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-23T17:19:43.702809+00:00'
[2024-11-23T19:19:59.253+0200] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-23T19:19:59.253+0200] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-23T19:19:59.253+0200] {logging_mixin.py:190} INFO - Current task name:update_patient_data state:running start_date:2024-11-23 17:19:59.107258+00:00
[2024-11-23T19:19:59.254+0200] {logging_mixin.py:190} INFO - Dag name:real_time_patient_data and current dag run status:running
[2024-11-23T19:19:59.254+0200] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-23T19:19:59.262+0200] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/munyah/airflow/dags/real_time_patient_data_update.py", line 51, in update_patient_data
    existing_ids = {patient['id'] for patient in all_patients}
  File "/home/munyah/airflow/dags/real_time_patient_data_update.py", line 51, in <setcomp>
    existing_ids = {patient['id'] for patient in all_patients}
KeyError: 'id'
[2024-11-23T19:19:59.269+0200] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-23T19:19:59.270+0200] {logging_mixin.py:190} INFO - Task start:2024-11-23 17:19:59.107258+00:00 end:2024-11-23 17:19:59.269352+00:00 duration:0.162094
[2024-11-23T19:19:59.270+0200] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): update_patient_data> dag:<DAG: real_time_patient_data> dagrun:<DagRun real_time_patient_data @ 2024-11-23 17:19:43.702809+00:00: manual__2024-11-23T17:19:43.702809+00:00, state:running, queued_at: 2024-11-23 17:19:43.721607+00:00. externally triggered: True>
[2024-11-23T19:19:59.270+0200] {logging_mixin.py:190} INFO - Failure caused by 'id'
[2024-11-23T19:19:59.271+0200] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=real_time_patient_data, task_id=update_patient_data, run_id=manual__2024-11-23T17:19:43.702809+00:00, execution_date=20241123T171943, start_date=20241123T171959, end_date=20241123T171959
[2024-11-23T19:19:59.283+0200] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-23T19:19:59.283+0200] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task update_patient_data ('id'; 407122)
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/munyah/airflow/dags/real_time_patient_data_update.py", line 51, in update_patient_data
    existing_ids = {patient['id'] for patient in all_patients}
  File "/home/munyah/airflow/dags/real_time_patient_data_update.py", line 51, in <setcomp>
    existing_ids = {patient['id'] for patient in all_patients}
KeyError: 'id'
[2024-11-23T19:19:59.314+0200] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-23T19:19:59.345+0200] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-23T19:19:59.345+0200] {local_task_job_runner.py:245} INFO - ::endgroup::
