[2025-03-10T21:11:26.523+0200] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T21:11:26.536+0200] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: patient-monitoring.add_new_patient scheduled__2025-03-10T19:10:00+00:00 [queued]>
[2025-03-10T21:11:26.542+0200] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: patient-monitoring.add_new_patient scheduled__2025-03-10T19:10:00+00:00 [queued]>
[2025-03-10T21:11:26.542+0200] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-10T21:11:26.556+0200] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): add_new_patient> on 2025-03-10 19:10:00+00:00
[2025-03-10T21:11:26.562+0200] {standard_task_runner.py:72} INFO - Started process 28122 to run task
[2025-03-10T21:11:26.567+0200] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'patient-monitoring', 'add_new_patient', 'scheduled__2025-03-10T19:10:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/real_time_patient_data_update.py', '--cfg-path', '/tmp/tmpbkqsso1w']
[2025-03-10T21:11:26.568+0200] {standard_task_runner.py:105} INFO - Job 90: Subtask add_new_patient
[2025-03-10T21:11:26.609+0200] {task_command.py:467} INFO - Running <TaskInstance: patient-monitoring.add_new_patient scheduled__2025-03-10T19:10:00+00:00 [running]> on host munyah-ThinkPad-X1-Yoga-1st
[2025-03-10T21:11:26.684+0200] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='munyah' AIRFLOW_CTX_DAG_ID='patient-monitoring' AIRFLOW_CTX_TASK_ID='add_new_patient' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T19:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-10T19:10:00+00:00'
[2025-03-10T21:11:26.685+0200] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-10T21:11:26.685+0200] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-10T21:11:26.686+0200] {logging_mixin.py:190} INFO - Current task name:add_new_patient state:running start_date:2025-03-10 19:11:26.536480+00:00
[2025-03-10T21:11:26.686+0200] {logging_mixin.py:190} INFO - Dag name:patient-monitoring and current dag run status:running
[2025-03-10T21:11:26.686+0200] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-10T21:11:26.706+0200] {real_time_patient_data_update.py:80} INFO - New Patient Added: {
  "Patient_ID": "PAT-00001",
  "Age": 6,
  "Gender": "Male",
  "Height": 177.48,
  "Weight": 159.73,
  "Temperature": 37.6,
  "Blood_Pressure": "92/61",
  "Cholesterol_Level": "Normal",
  "Blood_Sugar_Level": 205,
  "Heart_Rate": 54,
  "BMI": 43.69,
  "Previous_Medical_History": "No significant history",
  "Comorbidities": "None",
  "Smoking_Status": "Yes",
  "Alcohol_Consumption": "No",
  "Physical_Activity": "Low",
  "Last_Visit_Date": "2024-09-08",
  "Genomic_Info": "High Risk",
  "Diagnosis": "No specific diagnosis",
  "Hospitalization": "No"
}
[2025-03-10T21:11:26.706+0200] {real_time_patient_data_update.py:81} INFO - Total Patients After Addition: 1
[2025-03-10T21:11:26.713+0200] {base.py:84} INFO - Retrieving connection 'patients_data'
[2025-03-10T21:11:26.717+0200] {http.py:248} WARNING - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/add-patient (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b6fa4564be0>: Failed to establish a new connection: [Errno 111] Connection refused')) Tenacity will retry to execute the operation
[2025-03-10T21:11:26.718+0200] {real_time_patient_data_update.py:98} ERROR - Error while adding patient to the database: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/add-patient (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b6fa4564be0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2025-03-10T21:11:26.718+0200] {python.py:240} INFO - Done. Returned value was: None
[2025-03-10T21:11:26.722+0200] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-10T21:11:26.723+0200] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=patient-monitoring, task_id=add_new_patient, run_id=scheduled__2025-03-10T19:10:00+00:00, execution_date=20250310T191000, start_date=20250310T191126, end_date=20250310T191126
[2025-03-10T21:11:26.733+0200] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-10T21:11:26.733+0200] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-10T21:11:26.733+0200] {logging_mixin.py:190} INFO - Dag name:patient-monitoring queued_at:2025-03-10 19:11:13.147573+00:00
[2025-03-10T21:11:26.733+0200] {logging_mixin.py:190} INFO - Task hostname:munyah-ThinkPad-X1-Yoga-1st operator:PythonOperator
[2025-03-10T21:11:26.779+0200] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-10T21:11:26.795+0200] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T21:11:26.796+0200] {local_task_job_runner.py:245} INFO - ::endgroup::
